console.log("Anjika");
var firstname="Anjika";
var secondname="Ranjan";
console.log(secondname);
var fullname=firstname.concat(secondname);
console.log(fullname);
var length=fullname.length;
console.log(length);
var sentence="I am Anjika";
var word=sentence.replace("Anjika","Fathima");
console.log(sentence);
console.log(word);
var sentence1=sentence.toUpperCase();
console.log(sentence1);
var sentence2=sentence1.toLowerCase();
console.log(sentence2);
var squareroot=Math.sqrt(169);
console.log(squareroot);
var maxnumber=Math.max(74,47);
console.log(maxnumber);
var minnumber=Math.min(1000,2020);
console.log(minnumber);
var power=Math.pow(5,4);
console.log(power);